### ISSUE TITLE
Color changes

### ISSUE THREAD

**Issue by hpstephens** [zranger1/HubitatWizLightDriver#2]
I installed the latest driver and rebooted the hubitat. Now, the color change features are no longer working, especially under home app.

**Comment by hpstephens** [comment]
Would it be possible to have a dropdown for the different effects that are available?

**Comment by zranger1** [comment]
I've just updated the driver to fix this.  It actually fixes another long standing problem with the Hubitat's built in color bulb control UI too, so thanks for reporting this -- makes it better for everybody!

Get v1.2.2 from the repository or the package manager and let me know if it works for you.

(On the dropdown:  That's a Hubitat thing.  Their UI doesn't support this at the moment, but I know a lot of people have asked for it at various times, in several different contexts.  I'd like to have it too.)

**Comment by hpstephens** [comment]
Thanks
