### ISSUE TITLE
Bulbs come on at 10% intensity from on command

### ISSUE THREAD

**Issue by bmoulas** [zranger1/HubitatWizLightDriver#3]
I’m very new to his, have a slight problem where I turn a bulb on in the Hubitat device list and the bulb comes up to only 10% intensity.  I set the intensity to 100%, but the next time the bulb is turned on it goes to 10%, not its previous state even.

**Comment by bmoulas** [comment]
I rebooted my Hubitat and the problem went away.

**Comment by zranger1** [comment]
Thank you for keeping me posted and closing this!   I'm glad it went away w/reboot -- let me know if you see anything else.
