### ISSUE TITLE
Hubitat Overload of Events and States

### ISSUE THREAD

**Issue by jeanofthedead** [zranger1/HubitatWizLightDriver#6]
Ever since the Hubitat 2.2.8.141 update, I'm seeing a bazillion Events and States for my Wiz bulbs. I've even done a Soft Reset and set up the Hubitat again, so I'm not sure if it's an issue with my Hubitat or the device driver. Any suggestions?

<img width="1091" alt="Screen Shot 2021-07-23 at 16 14 45" src="https://user-images.githubusercontent.com/56093335/126849670-65d97ed7-244d-4824-8901-9df27e9cc4ab.png">

**Comment by zranger1** [comment]
Can you take a look at the events list for one of those devices and tell me what events it thinks it's logging?   They changed something about event logging in the latest firmware and it's not really documented.  I think I know what's going on, but I want to make sure you're seeing the same thing.

If the event names are all "rssi", as I suspect, you can get it to stop doing that 'till I get a real fix out by commenting out the line in the driver code (around line 296 or 297) that reads:

     ```sendEvent([name:"rssi", value: params.rssi);```

(change it to ```// sendEvent([name:"rssi", value: params.rssi);``` )

This won't have any effect on bulb operation.   RSSI is the wifi signal strength, which is reported when polling the bulb.  For some reason, the hub has decided that any minor fluctuation in signal strength, which happens constantly, is a state change that desperately needs to be logged.   There's not an obvious way to keep it from doing that, but I'm sure I can figure it out.  I do kinda wish they'd stop making unhelpful semi-random firmware changes like this though.

**Comment by jeanofthedead** [comment]
Yup, it's all RSSI events! You called it. I commented out the Device Driver line that you mentioned, and am monitoring the Hubitat Runtime Stats now. Will report back.
